# give to fix timeout issues temporarily (hint by travis support.)
sudo: required
dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10

# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn -Prun-its --show-version  -Dhttps.protocols=TLSv1.2 --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
